### ISSUE TITLE
Getting update notifications on mobile data but don't download the update?

### ISSUE THREAD

**Issue by wonder75** [chenxiaolong/Custota#104]
Hello, the documentation says:

> To reduce battery usage, the scheduling of the update checks is controlled by Android. They run at most once every 6 hours and will not run at all if the Require unmetered network or Require sufficient battery level conditions aren't met.

I am wondering now if it is possible to get notifications for new updates on mobile data without auto-downloading them.
Background is, that I use WiFi rarely and still would like to be informed about new updates.

I would like to connect to WiFi to download them when they are available, to save mobile data.

Is that possible?

**Comment by chenxiaolong** [comment]
This is currently not possible. The update check and update installation are part of the same scheduled job so they're both impacted by the unmetered network restriction.

I'll think about it more and see if there's an easy way to implement this when I'm back from vacation.

**Comment by chenxiaolong** [comment]
This has been implemented in #106 and will be included in version 5.3.

**Comment by wonder75** [comment]
Thank you very much, amazing. This makes it so much better for my usage case!
