### ISSUE TITLE
Doesn't work on Pixel 3 Emulator

### ISSUE THREAD

**Issue by thearsenaldevteam** [chenxiaolong/Custota#44]
When I ran this source code on Pixel 3 Emulator (android 13), the app crashed.
Can you help me check this?
<img width="1393" alt="Screenshot 2024-03-12 at 21 29 59" src="https://github.com/chenxiaolong/Custota/assets/14798909/a19b04c2-09e2-4323-a34f-d506e1d36b82">

**Comment by chenxiaolong** [comment]
Can you reupload the screenshot? It links back to this page.

**Comment by thearsenaldevteam** [comment]
> Can you reupload the screenshot? It links back to this page.

Yes, I updated the screenshot.

**Comment by chenxiaolong** [comment]
Ah, it's failing to query the bootloader status. I'm guessing the emulator doesn't implement the bootloader HAL (for querying locked bootloader status, etc.).

Do you know if OTA zips are available for the emulator? If not, I probably won't add a workaround for this since Custota wouldn't be able to install anything even if it could run.

**Comment by thearsenaldevteam** [comment]
> Ah, it's failing to query the bootloader status. I'm guessing the emulator doesn't implement the bootloader HAL (for querying locked bootloader status, etc.).
> 
> Do you know if OTA zips are available for the emulator? If not, I probably won't add a workaround for this since Custota wouldn't be able to install anything even if it could run.

I'm a newbie to OTA and just saw your project for the first time. I am sorry for my mistake but if you can fix it that's great.

**Comment by chenxiaolong** [comment]
Oh, no worries! I looked into it and it looks like Google does not provide OTA updates for emulators. Unfortunately, this means you'll have to use Custota on a real device.
