### ISSUE TITLE
Is it possible to replace custota-selinux with sesepolicy.rule on KernelSU to avoid being detected

### ISSUE THREAD

**Issue by jeffpeng3** [chenxiaolong/Custota#72]
I've noticed that a lot of modules that require modifications to the SELinux context use this approach, so I was curious if it could be done in this way and allow the root implementation to hide what might be detected.

sepolicy.rule Reference:
 - [KernelSU Side](https://kernelsu.org/guide/module.html#sepolicy-rule)
 - [Magisk Side](https://topjohnwu.github.io/Magisk/guides.html#sepolicyrule)

**Comment by chenxiaolong** [comment]
I don't think that would help. As far as I'm aware, magiskpolicy and custota-selinux both use the exact same approach to modifying the policy.

Custota does not use `sepolicy.rule` files because it's not flexible enough (it cannot copy SELinux types).

**Comment by chenxiaolong** [comment]
I think I might know what they're detecting. It's probably the file modification timestamp of `/sys/fs/selinux/load`.

I'm not interested in playing the cat and mouse game for hiding root, but in this case, the workaround should be easy enough. I'll give it a shot after work today.
