### ISSUE TITLE
Error - Failed to install OTA update: (Transaction failed on small parcel ...)

### ISSUE THREAD

**Issue by luxqaoa** [chenxiaolong/Custota#83]
Trying to perform OTA update with local installation source as suggested by this comment in [avbroot #357](https://github.com/chenxiaolong/avbroot/pull/357#issuecomment-2365343050). After checking for updates and pressing install, I get the notification 

```
Failed to install OTA update
DeadObjectException (Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe)
```
(see attached image below)

**What I did**

I followed these [steps](https://github.com/chenxiaolong/avbroot/pull/357#issuecomment-2365343050) up to step 8 to fix a previously discussed issue with avbroot. The issue happens after pressing "install" (the update), after pressing `Check for updates`. I installed Custota as a Magisk module.

Pressing "retry" results in the same error message.

Attempting to install a a [DivestOS image](https://divestos.org/mirror.php?base=LineageOS&f=sunfish/divested-20.0-20240907-dos-sunfish.zip) patched with avbroot 3.7.0

**Environment**

Custota 4.10 running on Windows 11 23H2 sandbox. Pixel 4a DivestOS with Magisk 26.4

**Attachments**

[Custota log files](https://gist.github.com/luxqaoa/da50d5c048d6cf43219f49ff28313a4d)

![bug](https://github.com/user-attachments/assets/670b9945-8083-4d53-9a9e-ba0c5a18d427)

**Comment by chenxiaolong** [comment]
Thanks for the logs! That was very helpful.

```
09-22 11:17:10.848  5026  5026 W Thread-8: type=1400 audit(0.0:1355): avc: denied { read } for path="/storage/emulated/0/custota/divested-20.0-20240907-dos-sunfish.zip.patched" dev="sdcardfs" ino=119299 scontext=u:r:update_engine:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0 app=com.chiller3.custota
```

Looks like the Pixel 4a uses sdcardfs for its internal storage. (Newer devices that shipped with Android 11 or newer [no longer use that](https://source.android.com/docs/core/storage/sdcardfs-deprecate) so I wasn't aware of it.)

The SELinux rules that Custota adds didn't account for sdcardfs, so Android's internal OTA updater component (update_engine) couldn't access your OTA file.

Can you please give this test build a try? [Custota-4.10.r4.g4ac7ee8-release.zip](https://github.com/user-attachments/files/17091552/Custota-4.10.r4.g4ac7ee8-release.zip) You can just flash this in Magisk--no need to repeat any of the other steps. If it still doesn't work, please upload the new logs.

**Comment by chenxiaolong** [comment]
That's progress, at least!

It looks like this issue is happening somewhere where Custota can't capture the logs. Could you run this:

```
adb shell su -c 'dmesg -w | grep avc:'
```

hit the `Install` button and then paste the output here once it fails? I'm hoping to see some message that mentions `sdcardfs`.

The output of this (after the error) would be helpful too:
```
adb logcat -s update_engine -d > update_engine.txt
```

**Comment by chenxiaolong** [comment]
Thanks! That should be easy to fix. Give me a couple minutes to make a new test build.

**Comment by chenxiaolong** [comment]
New test build: [Custota-4.10.r6.g5ce1c5a-release.zip](https://github.com/user-attachments/files/17103121/Custota-4.10.r6.g5ce1c5a-release.zip)

**Comment by chenxiaolong** [comment]
No problem, glad you got it working!
