### ISSUE TITLE
Custota crash getConfiguration()

### ISSUE THREAD

**Issue by iTzVirtual00** [chenxiaolong/Custota#97]
When I open the Custota it crashes instantly.
I'm using Kitsune magisk 27001 on GrapheneOS with Android 14.
I tried to fix by removing the module, rebooting, and reinstalling it. It is always the same error.
`/sdard/Android` (or any subdirectory) doesn't contain com.chiller3.custota and `/data/data/com.chiller3.custota` only has empty cache directories
I attached the crash logs and the logs located in /data/local/tmp
[Error in com.chiller3.custota.MainApplication d584f7c3529b.txt](https://github.com/user-attachments/files/17610949/Error.in.com.chiller3.custota.MainApplication.d584f7c3529b.txt)
[custota_selinux.log](https://github.com/user-attachments/files/17610952/custota_selinux.log)
[custota.log](https://github.com/user-attachments/files/17610953/custota.log)

Thanks

**Comment by chenxiaolong** [comment]
With Kitsune, you have to add Custota to the SuList, even though Custota doesn't use root privileges after it is installed. When it's not in the list, Kitsune prevents Android from accessing the `.apk`, which is what causes it to crash.
